CREATE DATABASE furniture;
\connect furniture

-- Создание таблицы для мебели
CREATE TABLE IF NOT EXISTS furniture
(
    id       INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name     VARCHAR(255),
    material VARCHAR(255),
    style    VARCHAR(255),
    price    DECIMAL,
    quantity INT
);

-- Вставка начальных данных для мебели
INSERT INTO furniture (name, material, style, price, quantity)
VALUES ('Table', 'wood', 'Modern', 10000, 1),
       ('Chair', 'wood', 'Classic', 5000, 4),
       ('Sofa', 'leather', 'Modern', 15000, 2),
       ('Bed', 'wood', 'Rustic', 12000, 1),
       ('Wardrobe', 'wood', 'Victorian', 25000, 1),
       ('Coffee Table', 'glass', 'Contemporary', 6000, 1),
       ('Bookshelf', 'wood', 'Modern', 7000, 2),
       ('Nightstand', 'wood', 'Classic', 3500, 2);

-- Создание таблицы пользователей
CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255)        NOT NULL
);

-- Создание таблицы ролей
CREATE TABLE IF NOT EXISTS roles
(
    id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) UNIQUE NOT NULL
);

-- Создание таблицы связей пользователей и ролей
CREATE TABLE IF NOT EXISTS user_roles
(
    user_id INT NOT NULL,
    role_id INT NOT NULL,
    CONSTRAINT fk_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_role
        FOREIGN KEY (role_id)
            REFERENCES roles (id)
            ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

-- Вставка начальных ролей
INSERT INTO roles (name)
VALUES ('User'),
       ('Admin');


-- Назначение роли администратора пользователю
INSERT INTO user_roles (user_id, role_id)
VALUES ((SELECT id FROM users WHERE username = 'admin'), (SELECT id FROM roles WHERE name = 'Admin'));
